language: java
jdk: oraclejdk7
before_install:
  # Install ia32-libs (necessary for Android SDK to run on 64-bit linux)
  # - sudo apt-get clean && sudo apt-get update
  - sudo apt-get update
  # Install Android SDK
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -zxf android-sdk_r22.3-linux.tgz
  - ls
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android list sdk --extended
  # Do you accept the license 'android-sdk-license-bcbbd656' [y/n]:
  - echo -e "y\n" > accept.txt
  - android update sdk --filter platform-tools,android-19 --no-ui --force
  - ls ${ANDROID_HOME}/platforms
  - cd ./AndroidAnnotationsExample
script:
  - ant debug
